Added a command line option to output a single hour
ibLeDy/timezone-converter pull request #16
Opened 2021-05-14 10:54 UTC by Badboy-16

I tried to fix #3 

I added the `-s` (`--single`) option to the command line input and enabled the programme to output a single hour.

Usage:
Output a single hour for current time.
```
$ timezone-converter hong_kong tokyo -s now
$ timezone-converter hong_kong tokyo --single now
```

Output a given hour specified by the user (e.g. 16).
```
$ timezone-converter hong_kong tokyo -s 16
$ timezone-converter hong_kong tokyo --single 16
```

2021-05-15 14:22 UTC, ibLeDy requested changes

2021-05-15 14:22 UTC, ibLeDy commented on timezone_converter/comparison_view.py
> +        self._print_with_rich(self._build_table(single_hour))
As suggested on `main.py`, we would use it as instance argument, so no need to pass it here.

2021-05-15 14:22 UTC, ibLeDy commented on timezone_converter/comparison_view.py
> +            hour_range = range(int(single_hour), int(single_hour) + 1)
I prefer to use something like we discussed in #15, a default value that will later change. I also prefer that the argument is just called `hour` (and that we provide it as an instance argument, as I mentioned in `main.py`). This is how this part would end up looking like:

```py
        hour_range = range(24)
        if self.hour is not None:
            hour_range = range(self.hour, self.hour + 1)
```

As I mentioned before, we would not use `now` and the current hour will be provided by `const` when no value is provided to `--single`.

We are also converting the value to `int` so no need to do it here.

2021-05-15 14:22 UTC, ibLeDy commented on timezone_converter/comparison_view.py
> +        for hour in hour_range:
As `current_hour` would only be used on this for loop, I would prefer that we move the `current_hour` declaration to the line before this one (line 64)

2021-05-15 14:22 UTC, ibLeDy commented on timezone_converter/comparison_view.py
> +    def _build_table(self, single_hour) -> Table:
As suggested on main.py, we would use it as instance argument, so no need to pass it here.

2021-05-16 13:47 UTC, Badboy-16 commented
Just pushed some commits based on your comments above. I think it's definitely a good idea to use a default value that can be changed later just like in #15 . Thanks for the reminder to utilise it again! 👍🏼 

I tested the output with the single hour option and it looks working fine.

2021-05-16 14:09 UTC, ibLeDy commented
pre-commit.ci run

2021-05-16 14:17 UTC, ibLeDy commented
We will have to wait a bit for `pre-commit` to run, because [seems like GitHub is having issues](https://www.githubstatus.com/):

![Screenshot from 2021-05-16 16-12-35](https://user-images.githubusercontent.com/45886240/118400455-f9905200-b661-11eb-8fac-f3d8b1262e7e.png)

2021-05-16 17:03 UTC, ibLeDy commented
pre-commit.ci run

2021-05-16 17:05 UTC, ibLeDy commented
pre-commit.ci autofix

2021-05-16 17:13 UTC, ibLeDy commented
This looks good, I will create a release in a bit, thanks!

2021-05-16 17:13 UTC, merged